apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffdl-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ffdl-operator
  template:
    metadata:
      labels:
        name: ffdl-operator
    spec:
      serviceAccountName: ffdl-operator
      containers:
        - name: ffdl-operator
          # Replace this with the built image name
          image: ffdlops/ffdl:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ffdl-operator"
            - name: FFDL_NAMESPACE
              value: "default"
            - name: FFDL_STORAGECLASS
              value: ""
            - name: FFDL_LOCALSTORAGE
              value: "true"
