kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ffdl-operator
subjects:
- kind: ServiceAccount
  name: ffdl-operator
  namespace: ffdl
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
